site_name: Blog Của Tao
theme:
  name: material
  features:
  - navigation.instant
  - navigation.sections
  - navigation.tabs
  - search.highlight
  - search.share
  - content.code.annotate
  - content.code.copy
  - content.action.edit
  - toc.integrate
  palette:
    scheme: slate
    primary: teal
    accent: teal
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
plugins:
- search
- git-revision-date-localized
- awesome-pages
- glightbox
nav:
- Trang chủ: index.md
- Ghi chú:
  - Ghi chú mẫu: ghi-chu/vi-du.md
- Blog:
  - Bài viết: blog/bai-viet.md
  - Bài viết test: blog/Cac-lenh-thao-tac-voi-Git.md
- Ý tưởng:
  - Ý tưởng hay: y-tuong/y-tuong-hay.md
